#!/usr/bin/env bash
# install and config ngnix in my sever

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.html
