#!/usr/bin/env bash
# install and config nginx in my server

apt update
apt install -y nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        
        root /var/www/html;
        index index.html;
        }" > /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx restart
