#!/usr/bin/env bash
#config a permanat redirection

old_str="#here_redirect_config"
redirect_path="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s|$old_str|$redirect_path|" /etc/nginx/sites-available/default
service nginx restart
