#!/usr/bin/env bash
#config a permanat redirection

new_string="\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"
sed -i "\$s|.*|$new_string|" /etc/nginx/sites-available/default
sudo service nginx restart
