#!/usr/bin/env bash
#config a new server and  permanat redirection and custom 404 error page + custom header

apt update
apt install -y nginx
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	location / {
		add_header X-Served-By $hostname;
		try_files $uri $uri/ =404;
	}

	# redirection config
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	# not found page 404
	error_page 404 /custom_404.html;
	location = /custom_404.html {
		internal;
	}
}" > /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
