#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt upgrade
apt install -y haproxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo "listen 48518-lb-01
  bind *:80
  mode http
  balance roundrobin
  option httpclose
  option forwardfor
  server 48518-web-02 100.26.234.235:80 check
  server 48518-web-01 100.25.211.4:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy start
