#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

sudo mysqldump -u root -p$1 --all-databases > backup.sql
now=$(date '+%d-%m-%Y')
tar -czvf $now.tar.gz backup.sql
