#!/usr/bin/env bash
# gets Apache to run on container and return a page containing Hello Holberton when querying the root of it

dpkg -s apache2 &> /dev/null
sudo apt-get update
sudo apt-get install apache2 -y
sudo ufw allow 'Apache'
service apache2 star
chmod "664" /var/www/html/index.html
echo 'Hello Holberton' > /var/www/html/index.html
