#!/usr/bin/env bash
# Config nginx so that it runs as nginx user and listen to all active IPs ports

sudo sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i '21s/.*/\tlisten 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i '22s/.*/\tlisten [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo service nginx restart
